server:
  port: 9205
spring:
  application:
    name: cql-proxy
  jackson:
    default-property-inclusion: non_null
eureka:
  instance:
    hostname: ${spring.application.name}
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://discovery:9102/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
