server:
  port: 9205
spring:
  application:
    name: cql-proxy
  jackson:
    default-property-inclusion: non_null
  zipkin:
    enabled: false
eureka:
  instance:
    hostname: ${spring.application.name}
    health-check-url-path: /actuator/health
  client:
    enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
