server:
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: on_param
    include-exception: true
spring:
  jackson:
    default-property-inclusion: non_null
